# fly.toml app configuration file generated for recipy-web on 2025-12-04T14:16:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'recipy-web'
primary_region = 'ams'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[env]
  PORT = '8080'
  RAILS_LOG_TO_STDOUT = '1'
  RAILS_SERVE_STATIC_FILES = 'true'

[processes]
  app = './bin/rails server -b 0.0.0.0 -p 8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # Temporarily disable health checks for debugging
  # [[http_service.checks]]
  #   interval = '10s'
  #   timeout = '2s'
  #   grace_period = '5s'
  #   method = 'GET'
  #   path = '/up'
  #   protocol = 'http'
  #   tls_skip_verify = false

  #   [http_service.checks.headers]
  #     X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
